---
  - name: add repo to repolist
    apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main' state=present
  
  - name: add docker key
    apt_key:
      keyserver: hkp://p80.pool.sks-keyservers.net:80
      id: 58118E89F3A912897C070ADBF76221572C52609D

  - name: install docker
    apt:
      name: docker-engine
      allow_unauthenticated: yes
      state: present